version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_itech
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: itech_support
      MYSQL_USER: useradmin
      MYSQL_PASSWORD: "itech1023522704@A"
      TZ: America/Bogota
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
    networks:
      - itech_network

  backend:
    build: ./backend
    container_name: backend_itech
    restart: always
    working_dir: /app
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: mysql
      TZ: America/Bogota
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    networks:
      - itech_network

  frontend:
    build: ./react-modulos/react-app
    container_name: frontend_itech
    restart: always
    environment:
      - NODE_ENV=production
      - TZ=America/Bogota
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - itech_network

volumes:
  mysql_data:

networks:
  itech_network:
    driver: bridge